import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Correctly set the favicon using rel="icon" */}
        <link
          rel="icon"
          href="/images/indigo-logo-transparent-128x52.png"
        />
      </Head>
      <body className={inter.className}>
        <Navbar />
        <main className="flex-grow pt-[4rem] md:pt-[4rem] lg:pt-[4rem] xl:pt-[4rem]">
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
